import { PT_Sans, Nunito } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation";

const ptSans = PT_Sans({ subsets: ["latin"], weight: ["700", "400"] });
const nunito = Nunito({ subsets: ["latin"], variable: "--font-nunito" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${ptSans.className} ${nunito.variable}`}>
      <body className="bg-light text-lg">
        <header>
          <Navigation />
        </header>
        {children}
      </body>
    </html>
  );
}
